name: Deploy MQTT Service

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging  
          - prod

env:
  TF_VERSION: '1.6.0'
  AWS_REGION: 'us-east-1'

jobs:
  deploy:
    name: Deploy MQTT to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: apis/infrastructure/iac/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Deploy Shared Networking
        working-directory: ./shared/networking
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan

      - name: Deploy MQTT Service
        working-directory: ./services/mqtt
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan

      - name: Output MQTT Endpoint
        working-directory: ./services/mqtt
        run: |
          echo "MQTT Endpoint:"
          terraform output mqtt_endpoint || echo "Run: aws iot describe-endpoint --endpoint-type iot:Data-ATS"
          terraform output mqtt_thing_name
          terraform output mqtt_dashboard_url




